### ISSUE TITLE
Structs, ref, constrained generics, static generic class codegen, unsafe refectlion via offset.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Leopotam/ecs#15]
Title codes right ecs to do and go with (I have full design in my head, need to write it down). I see you attempt to be futile. You may close this issues. But same time you may wait it upvoted or down voted. Or I will send example codes here.

https://www.youtube.com/watch?v=aKLntZcp27M

https://www.youtube.com/watch?v=4YTfxresvS8

Unity ECS lectures

id Software codes

https://www.youtube.com/watch?v=W3aieHjyNvw

Pseudo code:
```
static class Container
Container.Register<Position>()
Container.Register<Health>()
struct Player : IEntity<Position,Health>
{
  // some interface to push components
}
Container.Register<TE> where TE:IEntity<T1,T2> where T1 : unmanaged where T2 : unmanaged
Container.Registewr<Player>
```

This statics do reflection upon start and than do combnation of all IEntity, IEntity<T1,T2>, IEntity<T1,T15> to do calls and use Unsafe to set data by offset. Can get layout by using FieldInfo.

**Comment by Leopotam** [comment]
`LeoECS` designed to use classes instead of structs to can be used as multipurpose overall architecture solution for whole app / game, not just for corner-cases like "we need to simulate 10k particles as fast as possible". And it was developed for FW3.5 when no any `return refs` or 'local refs' were exists. At next new versions FW3.5 was dropped for using some `C#7.2` features, but structs still not planned.

> I see you attempt to be futile.

Better to stop spam useless offensive comments then.
