### ISSUE TITLE
Possibility to iterate over Entities in a Ecsworld instance?

### ISSUE THREAD

**Issue by DasHoern** [Leopotam/ecs#20]
Is it possible to iterate over every Entity in the Ecsworld?
I.e.
`foreach(EcsEntity entity in Ecsworld) {// do stuff with entity}`

**Comment by Leopotam** [comment]
There are no ways to iterate over all entities, Im not sure why you need it. You can iterate over filtered collection of entities with required components. Another way - you can create fake component and add it to each entity, then use `EcsFilter` with this component and iterate over it.

**Comment by DasHoern** [comment]
The reason i want to do this is that I am trying to serialize the EcsWorld into a .Json file, to save the current game state. I am currently trying to do it with the filtered Components instead, thank you for your very quick answer, wasn't quite expecting this. 👍

**Comment by Leopotam** [comment]
> i want to do this is that I am trying to serialize the EcsWorld into a .Json file

I dont recommend to do it in this way due to entities order (ids) not fixed and will be allocated / reused multiple times automatically during game run. It means - you cant serialize entities directly as named / guid-ed containers, you should to do it manually for required data. I even dont recommend to serialize ecs-components directly, better to create serializable-only types (structs for no additional memory allocations) and use them as bridge to serialize / deserialize.

Before deserialization you should cleanup `EcsWorld` somehow (removing old components through filters) or destroy old instance and create new one. Then - deserialize data and create new entities with new components.

> thank you for your very quick answer

Check `README` - at top section there are links to gitter-chat and discord-chat, maybe it will be faster to ask questions there.

**Comment by Leopotam** [comment]
@DasHoern is issue fixed for you? Can I close issue?

**Comment by DasHoern** [comment]
I found a way that should work, but thanks for your quick answer!
