### ISSUE TITLE
share game made with unity and this ecs system

### ISSUE THREAD

**Issue by a-gamedev** [Leopotam/ecs#31]
This is my game made with unity and this ecs system.
[link here](https://play.google.com/store/apps/details?id=com.agamedev.survivalwar)

**Comment by SH42913** [comment]
There is nothing to see here

**Comment by a-gamedev** [comment]
oh! my mistake...

**Comment by Leopotam** [comment]
@a-gamedev any issues during development?

**Comment by sunsetv8** [comment]
open source?

**Comment by alanyuen** [comment]
@Leopotam

1. No convenient get function to get access to EcsSystems if EcsWorld have multi EcsSystems.
2. No function enable or disable all run system in EcsSystems together.
3.  Previous version,OneFrame component may be removed before process because of EcsSystem's 
     execution sequence. Instead of use one frame component, i try remove entity manualy .
4. Do you suggest use event system (Dispatcher ) with ECS system?

**Comment by alanyuen** [comment]
@sunsetv8 

It is not open source. At least now.

**Comment by sunsetv8** [comment]
I just did as you say , i made a entity with eventComp like an "event msg",and i destroyed the eventEntity manualy. And i used a MessageBroker in UniRX, it work great~

**Comment by Leopotam** [comment]
@alanyuen 
> No convenient get function to get access to EcsSystems if EcsWorld have multi EcsSystems.

Because world should not know anything about any logic, its data holder, nothing more. You should keep created instances of worlds / ecssystems on your side.

> No function enable or disable all run system in EcsSystems together.

You can write extension method if you need this behaviour. Another way - you can nest `EcsSystems` to `EcsSystems` and disable all systems in nested `EcsSystems` with disabling this `EcsSystems` instance (it works like standard `IEcsRunSystem`).

> Previous version,OneFrame component may be removed before process because of EcsSystem's
execution sequence.

In current version you can set manually where `one-frame` component will be removed - order of `EcsSystems.OneFrame<>()` now important in registration and you move it between other systems.

> Do you suggest use event system (Dispatcher ) with ECS system?

I use `one-frame` components as short-live events and standard components with manual removal at end of action.

**Comment by alanyuen** [comment]
@Leopotam 

I understand what your mean.

Another issue:
The for loop here is not need when allow1 is false.

`
var allow1 = _allow1;
            for (int i = 0, iMax = entityData.ComponentsCountX2; i < iMax; i += 2) {
                var typeIdx = entityData.Components[i];
                var itemIdx = entityData.Components[i + 1];
                if (allow1 && typeIdx == EcsComponentType<Inc1>.TypeIndex) {
                    Get1[EntitiesCount] = (Inc1) entity.Owner.ComponentPools[typeIdx].Items[itemIdx];
                    allow1 = false;
                }
            }
`

**Comment by Leopotam** [comment]
@alanyuen its one unified "copy&paste" way to write filter code, can be wrapped to T4 or similar codegen later.
