### ISSUE TITLE
Suggestion: CreateEntityWithComponent/AddComponent should take already constructed component

### ISSUE THREAD

**Issue by kircher1** [Leopotam/ecs#4]
Moreover, it would be awesome to have corresponding functions that take multiple Components, i.e. CreateEntityWithComponents<T1, T2, T3>(comp1, comp2, comp3) and AddComponents<..etc...

**Comment by Leopotam** [comment]
> CreateEntityWithComponent/AddComponent should take already constructed component

Current implementation (throwing exception) - its some sort of protection programming, all checks will be removed in release builds. Why you cant get already added component at `AddComponent` method? Because otherwise you dont know - is this component was added right now or already exists, its very important for correct initialization of marshal-by-ref fields of component type (correctly recycling instances to pools, etc). Same behaviour for `RemoveComponent` method.

> it would be awesome to have corresponding functions that take multiple Components, i.e. CreateEntityWithComponents<T1, T2, T3>(comp1, comp2, comp3)

Good idea, can you create it as separate issue, please?

**Comment by Leopotam** [comment]
@kircher1 check 5ab0afc6ce21c3a6a3c4aac74521214d0434a096 commit at develop branch - there are new versions of `CreateEntityWith` method.
